version: '3.7'
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  mongo:
    image: mongo:4.2.2-bionic
    ports:
      - 27090:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - provisioning-mongo:/data/db
  mongo-express:
    image: mongo-express:0.49.0
    ports:
      - 8092:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
volumes:
  provisioning-mongo: {}
